// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: data.sql

package database

import (
	"context"
	"time"
)

const insertData = `-- name: InsertData :one
INSERT OR REPLACE INTO data (url, content, created_at, updated_at) VALUES (
	?,
	?,
	?,
	?
) RETURNING url
`

type InsertDataParams struct {
	Url       string
	Content   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) InsertData(ctx context.Context, arg InsertDataParams) (string, error) {
	row := q.db.QueryRowContext(ctx, insertData,
		arg.Url,
		arg.Content,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var url string
	err := row.Scan(&url)
	return url, err
}
